script:
##################
### Play Radio ###
##################

#######################
### Rádio Comercial ###
#######################

  radio_comercial_quarto:
    alias: Rádio Comercial Quarto
    sequence:
      - service: media_player.volume_set
        data:
          entity_id: media_player.nest_hub
          volume_level: '0.20'
      - service: media_player.play_media
        data_template:
          entity_id: media_player.nest_hub
          media_content_id: http://mcrscast1.mcr.iol.pt/comercial.mp3
          media_content_type: 'audio/mp4'
          
###########
### RFM ###
###########

  rfm_quarto:
    alias: RFM Quarto
    sequence:
      - service: media_player.volume_set
        data:
          entity_id: media_player.nest_hub
          volume_level: '0.20'
      - service: media_player.play_media
        data_template:
          entity_id: media_player.nest_hub
          media_content_id: https://20863.live.streamtheworld.com/RFM_SC
          media_content_type: 'audio/mp4'

###########
### M80 ###
###########
          
  m80_quarto:
    alias: M80 Quarto
    sequence:
      - service: media_player.volume_set
        data:
          entity_id: media_player.nest_hub
          volume_level: '0.20'
      - service: media_player.play_media
        data_template:
          entity_id: media_player.nest_hub
          media_content_id: http://mcrscast.mcr.iol.pt/m80
          media_content_type: 'audio/mp4'

################
### Vodafone ###
################

  vodafone_quarto:
    alias: Vodafone Quarto
    sequence:
      - service: media_player.volume_set
        data:
          entity_id: media_player.nest_hub
          volume_level: '0.20'
      - service: media_player.play_media
        data_template:
          entity_id: media_player.nest_hub
          media_content_id: http://195.23.102.207/vodafone
          media_content_type: 'audio/mp4'
          
################
### Nova Era ###
################
          
  nova_era_quarto:
    alias: Nova Era Quarto
    sequence:
      - service: media_player.volume_set
        data:
          entity_id: media_player.nest_hub
          volume_level: '0.20'
      - service: media_player.play_media
        data_template:
          entity_id: media_player.nest_hub
          media_content_id: http://centova.radios.pt:9478/stream/1/
          media_content_type: 'audio/mp4'
          
################
### Antena 3 ###
################
          
  antena3_quarto:
    alias: Antena 3 Quarto
    sequence:
      - service: media_player.volume_set
        data:
          entity_id: media_player.nest_hub
          volume_level: '0.20'
      - service: media_player.play_media
        data_template:
          entity_id: media_player.nest_hub
          media_content_id: http://radiocast.rtp.pt/antena380a.mp3
          media_content_type: 'audio/mp4'            

################
### Antena 1 ###
################

  antena1_quarto:
    alias: Antena 1 Quarto
    sequence:
      - service: media_player.volume_set
        data:
          entity_id: media_player.nest_hub
          volume_level: '0.20'
      - service: media_player.play_media
        data_template:
          entity_id: media_player.nest_hub
          media_content_id: http://radiocast.rtp.pt/antena180a.mp3
          media_content_type: 'audio/mp4'   
          
#################
### Cidade FM ###
#################

  cidadefm_quarto:
    alias: Cidade FM Quarto
    sequence:
      - service: media_player.volume_set
        data:
          entity_id: media_player.nest_hub
          volume_level: '0.20'
      - service: media_player.play_media
        data_template:
          entity_id: media_player.nest_hub
          media_content_id: http://mcrscast.mcr.iol.pt/cidadefm
          media_content_type: 'audio/mp4'  

################
### MegaHits ###
################
          
  megahits_quarto:
    alias: MegaHits Quarto
    sequence:
      - service: media_player.volume_set
        data:
          entity_id: media_player.nest_hub
          volume_level: '0.20'
      - service: media_player.play_media
        data_template:
          entity_id: media_player.nest_hub
          media_content_id: http://21313.live.streamtheworld.com/MEGA_HITS.mp3
          media_content_type: 'audio/mp4'  

###########
### TSF ###
###########

  tsf_quarto:
    alias: TSF Quarto
    sequence:
      - service: media_player.volume_set
        data:
          entity_id: media_player.nest_hub
          volume_level: '0.20'
      - service: media_player.play_media
        data_template:
          entity_id: media_player.nest_hub
          media_content_id: http://tsfdirecto.tsf.pt/tsfdirecto.mp3
          media_content_type: 'audio/mp4'