sensor:
###Antena 1###
    
  - platform: command_line
    name: Antena 1 Music
    command: "python3 /config/python_scripts/radio_details_antena_1.py TITULO"
    
  - platform: command_line
    name: Antena 1 Artist
    command: "python3 /config/python_scripts/radio_details_antena_1.py COMENT1"
    
  - platform: command_line
    name: imagem
    command: "python3 /config/python_scripts/radio_details_antena_1.py IMAGE"
    
  - platform: command_line
    name: StartTime
    command: "python3 /config/python_scripts/radio_details_antena_1.py realDateTime"
    
  - platform: command_line
    name: EndTime
    command: "python3 /config/python_scripts/radio_details_antena_1.py realEndDateTime"
    
  - platform: scrape
    resource: https://www.rtp.pt/antena1/
    name: Antena 1 Show Name
    select: ".clearfix.small"
    value_template: '{{ value }}' 

  - platform: template
    sensors:
      antena_1_radio_name:
        value_template: "Antena 1"
    
  - platform: scrape
    resource: https://media.rtp.pt/antena3/
    name: Antena 1 Show Hours
    select: ".program-caption"
    value_template: '{{ value.split(" ")[0]}}'  
    
  - platform: scrape
    resource: https://www.rtp.pt/antena1/
    name: Antena 1 Anim Name
    select: ".text-light.small"
    value_template: '{{ value }}' 
    
  - platform: template
    sensors:
      antena_1_album:
        friendly_name: Antena 1 Album
        value_template: >
          Sem Informação 
  
  - platform: scrape
    resource: https://www.rtp.pt/antena1/
    name: Antena 1 Album Cover
    select: ".img-responsive"
    attribute: src
    value_template: >
      {% if is_state('sensor.antena_3_album_cover', '') %}
        https://cdn-images.rtp.pt/common/img/channels/promos/player_A3.jpg
      {% else %}
        {{ value }}
      {% endif %}
