sensor:
###CIDADE FM###      

  - platform: scrape
    resource: https://cidade.iol.pt/nowplaying.xml
    name: CidadeFM Artist
    select: "DB_LEAD_ARTIST_NAME"
    value_template: >
      {% if is_state('sensor.cidadefm_artist', '') %}
        Sem Informação
      {% elif is_state('sensor.cidadefm_artist', 'unknown') %} 
        Sem Informação
      {% else %}
        {{ value }}
      {% endif %}
    
  - platform: scrape
    resource: https://cidade.iol.pt/nowplaying.xml
    name: CidadeFM Music
    select: "DB_DALET_TITLE_NAME"
    value_template: >
      {% if is_state('sensor.cidadefm_music', '') %}
        Sem Informação
      {% elif is_state('sensor.cidadefm_music', 'unknown') %} 
        Sem Informação
      {% else %}
        {{ value }}
      {% endif %}

  - platform: scrape
    resource: https://cidade.iol.pt/nowplaying.xml
    name: CidadeFM Album
    select: "DB_ALBUM_NAME"
    value_template: >
      {% if is_state('sensor.cidadefm_album', '') %}
        Sem Informação
      {% elif is_state('sensor.cidadefm_album', 'unknown') %} 
        Sem Informação
      {% else %}
        {{ value }}
      {% endif %}
    
  - platform: scrape
    resource: https://cidade.iol.pt/nowplaying.xml
    name: CidadeFM Show Name
    select: "SHOW_NAME"
    value_template: >
      {% if is_state('sensor.cidadefm_show_name', '') %}
        Sem Informação
      {% elif is_state('sensor.cidadefm_show_name', 'unknown') %} 
        Sem Informação
      {% else %}
        {{ value }}
      {% endif %}
    
  - platform: scrape
    resource: https://cidade.iol.pt/nowplaying.xml
    name: CidadeFM Show Hours
    select: "SHOW_HOURS"
    value_template: >
      {% if is_state('sensor.cidadefm_show_hours', '') %}
        Sem Informação
      {% elif is_state('sensor.cidadefm_show_hours', 'unknown') %} 
        Sem Informação
      {% else %}
        {{ value }}
      {% endif %}

  - platform: scrape
    resource: https://cidade.iol.pt/nowplaying.xml
    name: CidadeFM Rádio Name
    select: "DB_RADIO_NAME"
    value_template: >
      {% if is_state('sensor.cidadefm_radio_name', '') %}
        Sem Informação
      {% elif is_state('sensor.cidadefm_radio_name', 'unknown') %} 
        Sem Informação
      {% else %}
        {{ value }}
      {% endif %}

  - platform: scrape
    resource: https://cidade.iol.pt/nowplaying.xml
    name: CidadeFM Anim Name
    select: "NAME"
    value_template: >
      {% if is_state('sensor.cidadefm_anim_name', '') %}
        Sem Informação
      {% elif is_state('sensor.cidadefm_anim_name', 'unknown') %} 
        Sem Informação
      {% else %}
        {{ value }}
      {% endif %}
    
  - platform: scrape
    resource: https://cidade.iol.pt/nowplaying.xml
    name: CidadeFM Album Cover
    select: "DB_ALBUM_IMAGE"
    value_template: >
      {% if is_state('sensor.cidadefm_album_cover', '') %}
        NoAlbum
      {% else %}
        https://cidade.iol.pt/upload/album/{{ value }}
      {% endif %}