sensor:
###Rádio Comercial###
   
  - platform: scrape
    resource: https://radiocomercial.iol.pt/nowplaying.xml?_=1610636265896
    name: Comercial Artist
    select: "DB_LEAD_ARTIST_NAME"
    value_template: >
      {% if is_state('sensor.comercial_artist', '') %}
        Sem Informação
      {% elif is_state('sensor.comercial_artist', 'unknown') %} 
        Sem Informação
      {% else %}
        {{ value }}
      {% endif %}
    
  - platform: scrape
    resource: https://radiocomercial.iol.pt/nowplaying.xml?_=1610636265896
    name: Comercial Music
    select: "DB_SONG_NAME"
    value_template: >
      {% if is_state('sensor.comercial_music', '') %}
        Sem Informação
      {% elif is_state('sensor.comercial_music', 'unknown') %} 
        Sem Informação
      {% else %}
        {{ value }}
      {% endif %}

  - platform: scrape
    resource: https://radiocomercial.iol.pt/nowplaying.xml?_=1610636265896
    name: Comercial Album
    select: "DB_ALBUM_NAME"
    value_template: >
      {% if is_state('sensor.comercial_album', '') %}
        Sem Informação
      {% elif is_state('sensor.comercial_album', 'unknown') %} 
        Sem Informação
      {% else %}
        {{ value }}
      {% endif %}
    
  - platform: scrape
    resource: https://radiocomercial.iol.pt/nowplaying.xml?_=1610636265896
    name: Comercial Show Name
    select: "SHOW_NAME"
    value_template: >
      {% if is_state('sensor.comercial_show_name', '') %}
        Sem Informação
      {% elif is_state('sensor.comercial_show_name', 'unknown') %} 
        Sem Informação
      {% else %}
        {{ value }}
      {% endif %}
    
  - platform: scrape
    resource: https://radiocomercial.iol.pt/nowplaying.xml?_=1610636265896
    name: Comercial Show Hours
    select: "SHOW_HOURS"
    value_template: >
      {% if is_state('sensor.comercial_show_hours', '') %}
        Sem Informação
      {% elif is_state('sensor.comercial_show_hours', 'unknown') %} 
        Sem Informação
      {% else %}
        {{ value }}
      {% endif %}   
    
  - platform: scrape
    resource: https://radiocomercial.iol.pt/nowplaying.xml?_=1610636265896
    name: Comercial Anim Name
    select: "NAME"
    value_template: >
      {% if is_state('sensor.comercial_anim_name', '') %}
        Sem Informação
      {% elif is_state('sensor.comercial_anim_name', 'unknown') %} 
        Sem Informação
      {% else %}
        {{ value }}
      {% endif %}   

  - platform: scrape
    resource: https://radiocomercial.iol.pt/nowplaying.xml?_=1610636265896
    name: Comercial Rádio Name
    select: "DB_RADIO_NAME"
    value_template: >
      {% if is_state('sensor.comercial_radio_name', '') %}
        Sem Informação
      {% elif is_state('sensor.comercial_radio_name', 'unknown') %} 
        Sem Informação
      {% else %}
        {{ value }}
      {% endif %} 
    
  - platform: scrape
    resource: https://radiocomercial.iol.pt/nowplaying.xml?_=1610636265896
    name: Comercial Album Cover
    select: "DB_ALBUM_IMAGE"
    value_template: >
      {% if is_state('sensor.comercial_album_cover','') %}
        https://radiocomercial.iol.pt/upload/c/comercial.jpg
      {% else %}
        https://radiocomercial.iol.pt/upload/album/{{ value }}
      {% endif %}