sensor:
###megahits###

  - platform: command_line
    name: Megahits Artist
    command: "python3 /config/python_scripts/radio_details_megahits.py artist"
    
  - platform: command_line
    name: Megahits Music
    command: "python3 /config/python_scripts/radio_details_megahits.py name"
    
  - platform: command_line
    name: Megahits Album Cover
    command: "python3 /config/python_scripts/radio_details_megahits.py fundoxl"
    value_template: >
      {% if is_state('sensor.megahits_album_cover', 'https://cdnimages01.azureedge.net/megahits/None') %}
        https://cdnimages01.azureedge.net/megahits/mega7141b648_app_square.png
      {% else %}
        https://cdnimages01.azureedge.net/megahits/{{ value }}
      {% endif %}    
    
  - platform: scrape
    resource: https://megahits.sapo.pt/ouviremissao/Zm53OHFrRVVldFRwZllCYUdaa2NOdzY0WnZ0Zm42VXl4L0lyQ0N2TU1uRT0
    name: Megahits Show Name
    select: ".play-text-1"
    value_template: '{{ value }}'
    
  - platform: scrape
    resource: https://megahits.sapo.pt/ouviremissao/Zm53OHFrRVVldFRwZllCYUdaa2NOdzY0WnZ0Zm42VXl4L0lyQ0N2TU1uRT0
    name: Megahits Show Hours
    select: ".play-text-2"
    value_template: '{{ value }}'    
    
  - platform: scrape
    resource: https://megahits.sapo.pt/ouviremissao/Zm53OHFrRVVldFRwZllCYUdaa2NOdzY0WnZ0Zm42VXl4L0lyQ0N2TU1uRT0
    name: Megahits Anim Name
    select: ".play-text-1"
    value_template: '{{ value }}'

  - platform: scrape
    resource: https://megahits.sapo.pt/
    name: Megahits Rádio Name
    select: "title"
    value_template: '{{ value }}'
    
  - platform: template
    sensors: 
      megahits_album:
        value_template: >
          Sem Informação
      