sensor:
###Vodafone###
   
  - platform: scrape
    resource: https://vodafone.fm/nowplaying.xml
    name: Vodafone Artist
    select: "DB_LEAD_ARTIST_NAME"
    value_template: >
      {% if is_state('sensor.vodafone_artist', '') %}
        Sem Informação
      {% elif is_state('sensor.vodafone_artist', 'unavailable') %} 
        Sem Informação
      {% else %}
        {{ value }}
      {% endif %}
    
  - platform: scrape
    resource: https://vodafone.fm/nowplaying.xml
    name: Vodafone Music
    select: "DB_SONG_NAME"
    value_template: >
      {% if is_state('sensor.vodafone_music', '') %}
        Sem Informação
      {% elif is_state('sensor.vodafone_music', 'unavailable') %} 
        Sem Informação
      {% else %}
        {{ value }}
      {% endif %} 

  - platform: scrape
    resource: https://vodafone.fm/nowplaying.xml
    name: Vodafone Album
    select: "DB_ALBUM_NAME"
    value_template: >
      {% if is_state('sensor.vodafone_album', '') %}
        Sem Informação
      {% elif is_state('sensor.vodafone_album', 'unavailable') %} 
        Sem Informação
      {% else %}
        {{ value }}
      {% endif %}
    
  - platform: scrape
    resource: https://vodafone.fm/nowplaying.xml
    name: Vodafone Show Name
    select: "SHOW_NAME"
    value_template: >
      {% if is_state('sensor.vodafone_show_name', '') %}
        Sem Informação
      {% elif is_state('sensor.vodafone_show_name', 'unavailable') %} 
        Sem Informação
      {% else %}
        {{ value }}
      {% endif %}

  - platform: scrape
    resource: https://vodafone.fm/nowplaying.xml
    name: Vodafone Rádio Name
    select: "DB_RADIO_NAME"
    value_template: >
      {% if is_state('sensor.vodafone_radio_name', '') %}
        Sem Informação
      {% elif is_state('sensor.vodafone_radio_name', 'unavailable') %} 
        Sem Informação
      {% else %}
        {{ value }}
      {% endif %} 
    
  - platform: template
    sensors:
      vodafone_show_hours:
        friendly_name: Vodafone Show Hours
        value_template: "Sem Informação"
    
  - platform: scrape
    resource: https://vodafone.fm/nowplaying.xml
    name: Vodafone Anim Name
    select: "NAME"
    value_template: >
      {% if is_state('sensor.vodafone_anim_name', '') %}
        Sem Informação
      {% elif is_state('sensor.vodafone_anim_name', 'unavailable') %} 
        Sem Informação
      {% else %}
        {{ value }}
      {% endif %} 
    
  - platform: scrape
    resource: https://vodafone.fm/nowplaying.xml
    name: Vodafone Album Cover
    select: "DB_ALBUM_IMAGE"
    value_template: >
      {% if is_state('sensor.vodafone_album_cover', '') %}
        https://vodafone.fm/images/fbcover.jpg
      {% else %}
        https://vodafone.fm/upload/album/{{ value }}
      {% endif %}
