sensor:
###M80###      

  - platform: scrape
    resource: https://m80.iol.pt/nowplaying.xml
    name: M80 Artist
    select: "DB_LEAD_ARTIST_NAME"
    value_template: >
      {% if is_state('sensor.m80_artist', '') %}
        Sem Informação
      {% elif is_state('sensor.m80_artist', 'unknown') %} 
        Sem Informação
      {% else %}
        {{ value }}
      {% endif %} 
    
  - platform: scrape
    resource: https://m80.iol.pt/nowplaying.xml
    name: M80 Music
    select: "DB_DALET_TITLE_NAME"
    value_template: >
      {% if is_state('sensor.m80_music', '') %}
        Sem Informação
      {% elif is_state('sensor.m80_music', 'unknown') %} 
        Sem Informação
      {% else %}
        {{ value }}
      {% endif %}

  - platform: scrape
    resource: https://m80.iol.pt/nowplaying.xml
    name: M80 Album
    select: "DB_ALBUM_NAME"
    value_template: >
      {% if is_state('sensor.m80_album', '') %}
        Sem Informação
      {% elif is_state('sensor.m80_album', 'unknown') %} 
        Sem Informação
      {% else %}
        {{ value }}
      {% endif %}
    
  - platform: scrape
    resource: https://m80.iol.pt/nowplaying.xml
    name: M80 Show Name
    select: "SHOW_NAME"
    value_template: >
      {% if is_state('sensor.m80_show_name', '') %}
        Sem Informação
      {% elif is_state('sensor.m80_show_name', 'unknown') %} 
        Sem Informação
      {% else %}
        {{ value }}
      {% endif %}
    
  - platform: scrape
    resource: https://m80.iol.pt/nowplaying.xml
    name: M80 Anim Name
    select: "NAME"
    value_template: >
      {% if is_state('sensor.m80_anim_name', '') %}
        Sem Informação
      {% elif is_state('sensor.m80_anim_name', 'unknown') %} 
        Sem Informação
      {% else %}
        {{ value }}
      {% endif %}
    
  - platform: scrape
    resource: https://m80.iol.pt/nowplaying.xml
    name: M80 Show hours
    select: "SHOW_HOURS"
    value_template: >
      {% if is_state('sensor.m80_show_hours', '') %}
        Sem Informação
      {% elif is_state('sensor.m80_show_hours', 'unknown') %} 
        Sem Informação
      {% else %}
        {{ value }}
      {% endif %}

  - platform: scrape
    resource: https://m80.iol.pt/nowplaying.xml
    name: M80 Rádio Name
    select: "DB_RADIO_NAME"
    value_template: >
      {% if is_state('sensor.m80_radio_name', '') %}
        Sem Informação
      {% elif is_state('sensor.m80_radio_name', 'unknown') %} 
        Sem Informação
      {% else %}
        {{ value }}
      {% endif %}       

    
  - platform: scrape
    resource: https://m80.iol.pt/nowplaying.xml
    name: M80 Album Cover
    select: "DB_ALBUM_IMAGE"
    value_template: >
      {% if is_state('sensor.m80_album_cover', '') %}
        https://m80.iol.pt/images/logo-m80.svg
      {% else %}
        https://m80.iol.pt/upload/album/{{ value }}
      {% endif %}