sensor:
###RFM###

  - platform: command_line
    name: RFM Artist
    command: "python3 /config/python_scripts/radio_details_rfm.py artist"
    value_template: >
      {% if is_state('sensor.rfm_artist', '') %}
        Sem Informação
      {% elif is_state('sensor.rfm_artist', 'unknown') %} 
        Sem Informação
      {% else %}
        {{ value }}
      {% endif %}
    
  - platform: command_line
    name: RFM Music
    command: "python3 /config/python_scripts/radio_details_rfm.py name"
    value_template: >
      {% if is_state('sensor.rfm_music', '') %}
        Sem Informação
      {% elif is_state('sensor.rfm_music', 'unknown') %} 
        Sem Informação
      {% else %}
        {{ value }}
      {% endif %}    
    
  - platform: command_line
    name: RFM Album Cover
    command: "python3 /config/python_scripts/radio_details_rfm.py capa"
    value_template: >
      {% if is_state('sensor.rfm_album_cover', '') %}
        https://cdnimages01.azureedge.net/rfm/default300x3002255339a_117162246.jpg
      {% else %}
        https://cdnimages01.azureedge.net/rfm/{{ value }}
      {% endif %}    
      
  - platform: template
    sensors:
      rfm_album:
        friendly_name: RFM Album
        value_template: >
          Sem Informação 
    
  - platform: scrape
    resource: https://rfm.sapo.pt/
    name: RFM Show Name
    select: "#marqueeBoxTime2"
    value_template: >
      {% if is_state('sensor.rfm_show_name', '') %}
        Sem Informação
      {% elif is_state('sensor.rfm_show_name', 'unknown') %} 
        Sem Informação
      {% else %}
        {{ value }}
      {% endif %}
    
  - platform: scrape
    resource: https://rfm.sapo.pt/
    name: RFM Show Hours
    select: ".marqueeBoxTime"
    value_template: >
      {% if is_state('sensor.rfm_show_hours', '') %}
        Sem Informação
      {% elif is_state('sensor.rfm_show_hours', 'unknown') %} 
        Sem Informação
      {% else %}
        {{ value }}
      {% endif %}
   
    
  - platform: scrape
    resource: https://rfm.sapo.pt/
    name: RFM Anim Name
    select: ".marqueeBoxAnim"
    value_template: >
      {% if is_state('sensor.rfm_anim_name', '') %}
        Sem Informação
      {% elif is_state('sensor.rfm_anim_name', 'unknown') %} 
        Sem Informação
      {% else %}
        {{ value }}
      {% endif %}

  - platform: scrape
    resource: https://rfm.sapo.pt/
    name: RFM Rádio Name
    select: "title"
    value_template: '{{ value }}'
    
      