sensor:
##TSF###      

  - platform: template
    sensors:
      tsf_geral:
        friendly_name: TSF Geral
        value_template: "Sem Informação"
    
  - platform: scrape
    resource: https://www.tsf.pt/emdirecto.html
    name: TSF Album Cover
    select: "DB_ALBUM_IMAGE"
    value_template: >
      https://cdn.worldvectorlogo.com/logos/tsf.svg